version: '3'

services:
  app:
    build: .
    environment:
      VIRTUAL_HOST: preprod.camino.beta.gouv.fr
      VIRTUAL_PORT: ${NODE_PORT}
      LETSENCRYPT_HOST: preprod.camino.beta.gouv.fr
      LETSENCRYPT_EMAIL: risseraka@gmail.com
    expose:
      - ${NODE_PORT}

networks:
  default:
    external:
      name: nginx-proxy
