version: '3'

services:
  app:
    build: .
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${NODE_PORT}
      LETSENCRYPT_HOST: ${URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - ${NODE_PORT}

networks:
  default:
    external:
      name: nginx-proxy
