version: '3'

services:
  app:
    build: .
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${NODE_PORT}
    expose:
      - ${NODE_PORT}

networks:
  default:
    external:
      name: nginx-proxy
